#!/bin/bash
# init.sh — Interactive setup wizard for junior-mem
# Creates directory structure, config.json, and validates model connectivity

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PLUGIN_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
KNOWLEDGE_DIR="${KNOWLEDGE_DIR:-$HOME/.claude/knowledge}"

# Parse flags
NON_INTERACTIVE=false
for arg in "$@"; do
  case "$arg" in
    --non-interactive|-y) NON_INTERACTIVE=true ;;
    --help|-h)
      echo "Usage: bash init.sh [--non-interactive]"
      echo "  --non-interactive  Use defaults, no prompts"
      exit 0 ;;
  esac
done

# ── Colors ───────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
BLUE='\033[0;34m'; CYAN='\033[0;36m'; BOLD='\033[1m'
DIM='\033[2m'; NC='\033[0m'

info()  { echo -e "${BLUE}  ℹ${NC} $*"; }
ok()    { echo -e "${GREEN}  ✔${NC} $*"; }
warn()  { echo -e "${YELLOW}  ⚠${NC} $*"; }
fail()  { echo -e "${RED}  ✘${NC} $*"; }
header(){ echo -e "\n${BOLD}${CYAN}$*${NC}\n"; }

prompt_default() {
  local var="$1" label="$2" default="$3"
  echo -ne "  ${BOLD}${label}${NC} [${DIM}${default}${NC}]: "
  read -r val
  val="${val:-$default}"
  eval "$var=\$val"
}

select_option() {
  local var="$1" label="$2"; shift 2
  local options=("$@")
  echo -e "  ${BOLD}${label}${NC}"
  local i=1
  for opt in "${options[@]}"; do
    echo -e "    ${CYAN}${i}${NC}) ${opt}"
    ((i++))
  done
  echo -ne "  ${BOLD}Select${NC} [1]: "
  read -r choice
  choice="${choice:-1}"
  if [[ "$choice" =~ ^[0-9]+$ ]] && [[ "$choice" -ge 1 ]] && [[ "$choice" -le "${#options[@]}" ]]; then
    eval "$var=\${options[$((choice-1))]}"
  else
    eval "$var=\${options[0]}"
  fi
}

validate_model() {
  local model="$1" label="$2"
  info "Validating ${BOLD}${model}${NC} (${label})..."
  local result
  if result=$(timeout 30 claude -p --model "$model" "reply with exactly: ok" </dev/null 2>&1); then
    if echo "$result" | grep -qi "ok"; then
      ok "${model} available — ${DIM}${result}${NC}"
      return 0
    else
      ok "${model} responded — ${DIM}${result:0:40}${NC}"
      return 0
    fi
  else
    fail "${model} no response: ${result:0:60}"
    return 1
  fi
}

write_config() {
  cat > "$CONFIG_FILE" << CONFEOF
{
  "model_cheap": "${MODEL_CHEAP}",
  "model_strong": "${MODEL_STRONG}",
  "knowledge_dir": "${KNOWLEDGE_DIR}",
  "soft_limit": ${SOFT_LIMIT},
  "claude_cmd": "claude",
  "cron_schedule": "${CRON_SCHEDULE}",
  "initialized_at": "$(date -Iseconds)"
}
CONFEOF
  ok "config.json written"
}

setup_cron() {
  local schedule="$1" script="$2"
  local cron_line="${schedule} ${script} >> ${KNOWLEDGE_DIR}/consolidation.log 2>&1"
  crontab -l 2>/dev/null | grep -v "consolidate.sh" | crontab - 2>/dev/null || true
  (crontab -l 2>/dev/null; echo "$cron_line") | crontab -
  ok "cron configured: ${schedule}"
}

# ── Non-interactive init ──────────────────────────────────────────────

detect_models() {
  # Auto-detect from env vars (set by Claude Code session)
  MODEL_CHEAP="${ANTHROPIC_DEFAULT_HAIKU_MODEL:-claude-haiku-4-5-20251001}"
  MODEL_STRONG="${ANTHROPIC_DEFAULT_OPUS_MODEL:-claude-opus-4-7}"
  # Fallback: check settings.json
  if [[ -f "$HOME/.claude/settings.json" ]]; then
    [[ -z "$MODEL_CHEAP" || "$MODEL_CHEAP" == "claude-haiku-4-5-20251001" ]] && \
      MODEL_CHEAP=$(jq -r '.env.ANTHROPIC_DEFAULT_HAIKU_MODEL // "claude-haiku-4-5-20251001"' "$HOME/.claude/settings.json" 2>/dev/null)
    [[ -z "$MODEL_STRONG" || "$MODEL_STRONG" == "claude-opus-4-7" ]] && \
      MODEL_STRONG=$(jq -r '.env.ANTHROPIC_DEFAULT_OPUS_MODEL // "claude-opus-4-7"' "$HOME/.claude/settings.json" 2>/dev/null)
  fi
  export MODEL_CHEAP MODEL_STRONG
}

non_interactive_init() {
  detect_models
  local soft_limit="${1:-1000}"

  mkdir -p "$KNOWLEDGE_DIR"/{staging/processed,active,archive,consolidation}

  CONFIG_FILE="$KNOWLEDGE_DIR/config.json"
  if [[ -f "$CONFIG_FILE" ]]; then
    echo "Already initialized: $CONFIG_FILE"
    return 0
  fi

  SOFT_LIMIT="$soft_limit"
  CRON_SCHEDULE="0 3 * * *"
  write_config
  setup_cron "$CRON_SCHEDULE" "$SCRIPT_DIR/consolidate.sh"

  if [[ ! -f "$KNOWLEDGE_DIR/state.json" ]]; then
    cat > "$KNOWLEDGE_DIR/state.json" << 'EOF'
{
  "total_active": 0,
  "total_archive": 0,
  "consecutive_failures": 0,
  "last_success_date": null,
  "last_consolidation": null
}
EOF
  fi

  if [[ ! -f "$KNOWLEDGE_DIR/INDEX.md" ]]; then
    cat > "$KNOWLEDGE_DIR/INDEX.md" << 'EOF'
# Knowledge Index

_Auto-generated by consolidation. Do not edit manually._

(No entries yet)
EOF
  fi

  touch "$KNOWLEDGE_DIR/access_log.jsonl"

  # Install better-sqlite3 if needed
  if [[ ! -d "$PLUGIN_DIR/node_modules/better-sqlite3" ]]; then
    (cd "$PLUGIN_DIR" && npm install better-sqlite3 2>/dev/null) || true
  fi

  echo "Initialized: $KNOWLEDGE_DIR"
  echo "  model_cheap:  $MODEL_CHEAP"
  echo "  model_strong: $MODEL_STRONG"
  echo "  soft_limit:   $SOFT_LIMIT"
}

# ══════════════════════════════════════════════════════════════════════
# Main
# ══════════════════════════════════════════════════════════════════════

if [[ "$NON_INTERACTIVE" == "true" ]]; then
  non_interactive_init
  exit $?
fi

header "╔═══════════════════════════════════════╗
║  junior-mem Knowledge System — Setup   ║
╚═════════════════════════════════════════╝"

# ── Step 0: Prerequisites ────────────────────────────────────────────
header "Step 0/4 — Prerequisites"

local_fail=0
command -v jq >/dev/null 2>&1 && ok "jq installed" || { fail "jq not found (apt install jq)"; local_fail=1; }
command -v claude >/dev/null 2>&1 && ok "claude CLI installed" || { fail "claude CLI not found"; local_fail=1; }
command -v node >/dev/null 2>&1 && ok "node installed" || { fail "node not found"; local_fail=1; }
# Check better-sqlite3
if [[ -d "$PLUGIN_DIR/node_modules/better-sqlite3" ]]; then
  ok "better-sqlite3 installed"
else
  warn "better-sqlite3 not found, installing..."
  (cd "$PLUGIN_DIR" && npm install better-sqlite3 2>/dev/null) && ok "better-sqlite3 installed" || { fail "better-sqlite3 install failed"; local_fail=1; }
fi

if [[ "$local_fail" -eq 1 ]]; then
  echo ""
  fail "Missing dependencies. Please install them and try again."
  exit 1
fi

# ── Step 1: Directories ─────────────────────────────────────────────
header "Step 1/4 — Directory Configuration"

prompt_default KNOWLEDGE_DIR "Knowledge storage directory" "$KNOWLEDGE_DIR"
mkdir -p "$KNOWLEDGE_DIR"/{staging/processed,active,archive,consolidation}
ok "Directories created: ${KNOWLEDGE_DIR}"

CONFIG_FILE="$KNOWLEDGE_DIR/config.json"

# ── Step 2: Model selection ─────────────────────────────────────────
header "Step 2/4 — Model Configuration"

info "The consolidation pipeline needs two models:"
echo -e "  ${DIM}  cheap  = Scanner/Challenger/Auditor/Validator (classification, high volume)${NC}"
echo -e "  ${DIM}  strong = Executor (writes human-readable documents)${NC}"
echo ""

# Detect available models from current settings
CURRENT_HAIKU="" CURRENT_SONNET="" CURRENT_OPUS=""
if [[ -f "$HOME/.claude/settings.json" ]]; then
  CURRENT_OPUS=$(jq -r '.env.ANTHROPIC_DEFAULT_OPUS_MODEL // ""' "$HOME/.claude/settings.json" 2>/dev/null)
  CURRENT_SONNET=$(jq -r '.env.ANTHROPIC_DEFAULT_SONNET_MODEL // ""' "$HOME/.claude/settings.json" 2>/dev/null)
  CURRENT_HAIKU=$(jq -r '.env.ANTHROPIC_DEFAULT_HAIKU_MODEL // ""' "$HOME/.claude/settings.json" 2>/dev/null)
fi

# Cheap model
echo -e "  ${BOLD}[Cheap Model]${NC} for 4 classification stages"
MODEL_OPTIONS_CHEAP=("claude-haiku-4-5-20251001" "claude-sonnet-4-6" "${CURRENT_HAIKU:-haiku}" "${CURRENT_SONNET:-sonnet}" "Custom")
select_option MODEL_CHEAP "Select cheap model" "${MODEL_OPTIONS_CHEAP[@]}"
if [[ "$MODEL_CHEAP" == "Custom" ]]; then
  prompt_default MODEL_CHEAP "Enter model name" "claude-haiku-4-5-20251001"
fi

# Strong model
echo ""
echo -e "  ${BOLD}[Strong Model]${NC} for Executor (document generation)"
MODEL_OPTIONS_STRONG=("claude-opus-4-7" "claude-sonnet-4-6" "${CURRENT_OPUS:-opus}" "${CURRENT_SONNET:-sonnet}" "Custom")
select_option MODEL_STRONG "Select strong model" "${MODEL_OPTIONS_STRONG[@]}"
if [[ "$MODEL_STRONG" == "Custom" ]]; then
  prompt_default MODEL_STRONG "Enter model name" "claude-opus-4-7"
fi

# Validate models
echo ""
CHEAP_OK=0 STRONG_OK=0
validate_model "$MODEL_CHEAP" "cheap" && CHEAP_OK=1 || warn "Cheap model validation failed, test manually later"
validate_model "$MODEL_STRONG" "strong" && STRONG_OK=1 || warn "Strong model validation failed, test manually later"

# ── Step 3: Parameters ──────────────────────────────────────────────
header "Step 3/4 — Parameters"

prompt_default SOFT_LIMIT "Knowledge entry soft limit" "1000"
select_option CRON_ANSWER "Configure cron for automatic consolidation?" "Yes — daily at 3am" "No — run manually"
if [[ "$CRON_ANSWER" == "Yes — daily at 3am" ]]; then
  CRON_SCHEDULE="0 3 * * *"
else
  CRON_SCHEDULE=""
fi

# ── Step 4: Write config & finalize ─────────────────────────────────
header "Step 4/4 — Writing Configuration"

write_config

if [[ ! -f "$KNOWLEDGE_DIR/state.json" ]]; then
  cat > "$KNOWLEDGE_DIR/state.json" << 'EOF'
{
  "total_active": 0,
  "total_archive": 0,
  "consecutive_failures": 0,
  "last_success_date": null,
  "last_consolidation": null
}
EOF
  ok "state.json created"
fi

if [[ ! -f "$KNOWLEDGE_DIR/INDEX.md" ]]; then
  cat > "$KNOWLEDGE_DIR/INDEX.md" << 'EOF'
# Knowledge Index

_Auto-generated by consolidation. Do not edit manually._

(No entries yet)
EOF
  ok "INDEX.md created"
fi

touch "$KNOWLEDGE_DIR/access_log.jsonl"

if [[ -n "$CRON_SCHEDULE" ]]; then
  setup_cron "$CRON_SCHEDULE" "$SCRIPT_DIR/consolidate.sh"
fi

# ── Summary ─────────────────────────────────────────────────────────
header "═══ Initialization Complete ═══"

echo -e "  ${BOLD}Config file:${NC}   ${CONFIG_FILE}"
echo -e "  ${BOLD}Cheap model:${NC}  ${MODEL_CHEAP} $([[ $CHEAP_OK -eq 1 ]] && echo -e "${GREEN}✔${NC}" || echo -e "${YELLOW}⚠ not verified${NC}")"
echo -e "  ${BOLD}Strong model:${NC} ${MODEL_STRONG} $([[ $STRONG_OK -eq 1 ]] && echo -e "${GREEN}✔${NC}" || echo -e "${YELLOW}⚠ not verified${NC}")"
echo -e "  ${BOLD}Knowledge dir:${NC} ${KNOWLEDGE_DIR}"
echo -e "  ${BOLD}Soft limit:${NC}   ${SOFT_LIMIT} entries"
echo -e "  ${BOLD}Cron schedule:${NC} ${CRON_SCHEDULE:-manual}"
echo ""
echo -e "  ${DIM}Edit config: jq . ${CONFIG_FILE}${NC}"
echo -e "  ${DIM}Run consolidation: KNOWLEDGE_DIR=${KNOWLEDGE_DIR} bash ${SCRIPT_DIR}/consolidate.sh${NC}"
echo -e "  ${DIM}Check status: KNOWLEDGE_DIR=${KNOWLEDGE_DIR} bash ${SCRIPT_DIR}/diagnose.sh status${NC}"
